//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestauranteMobile.RestauranteService {
    using System.Runtime.Serialization;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="StatusComando", Namespace="http://schemas.datacontract.org/2004/07/RestauranteService")]
    public enum StatusComando : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ConcluidoSucesso = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroExecucao = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ErroDados = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        OperacaoNaoPermitida = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SolicitacaoAdministrador = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        MesaAberta = 5,
    }
}
